---

- name: Configure ElasticSearch
  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: elasticsearch reload

- name: Setup JVM options
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: "{{ item.regexp }}"
    line: "{{ item.replace }}"
  with_items:
    - { regexp: '^-Xms', replace: '-Xms{{ xms }}'}
    - { regexp: '^-Xmx', replace: '-Xmx{{ xmx }}'}
  notify: elasticsearch reload

- name: Enable Lock Memory
  lineinfile:
    path: /usr/lib/systemd/system/elasticsearch.service
    insertafter: '^# Disable timeout'
    line: 'LimitMEMLOCK=infinity'
  notify: reload systemd